### ISSUE TITLE
Pre-Release checklist

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#20]
- [ ] data API up-and-running
- [x] unittests imlplemented
- [ ] coverage is tracked
- [ ] linting for PR implemented
- [ ] documentation up-and-running
