### ISSUE TITLE
Data publication

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/RUINSapp#85]
@cojacoo, @jonaslenz, @AlexDo1, @lucfr 
This is our main issue related to the planned data publication on Zenodo. 

I added a README into the data folder. This will be the main source of information for users (scientists) who download the data directly from Zenodo. In a final version it should include a listing of all files and the origins; a statement about processing; a hint how to load or use the data and finally a description of the structure. For now, we only need the listing and the origin statement. Then, a preliminary Zenodo version can be published to implement the download function into RUINS. 

The current state of the data folder can be downloaded here: http://ruins.hydrocode.de/data.zip
You can double-check, that all needed data is included.

## TODOs

- [ ] Update `cordex_krummh` to include all ET data - @cojacoo 
- [ ] Convert the `krummhoern/*` files into the missing `hydro_krummh.nc` file - @jonaslenz / @lucfr / @mmaelicke 
- [ ] add statements about data origin - @cojacoo

**Comment by mmaelicke** [comment]
And: @cojacoo - you need to specify the list of authors (and order) for that data publication. I am not sure, who contributed.

**Comment by AlexDo1** [comment]
I just tested weather.py with the new data in this [branch](https://github.com/hydrocode-de/RUINSapp/tree/config_datafile_names).
Everything seems to work with the new data files as all of the plots are still shown.
